package com.penske.products.fleetinsight.context;

public enum ContextKeyFI {
    API_REQUEST_PARAMETERS,
    API_RESPONSE,
    API_RESPONSE_LOGGER,
    COUNT_USERS_ON_ADMIN_TOOLS_PAGE,
    CURRENT_USER_COMPANY_ID,
    CUSTOM_GROUP_MANAGEMENT_PAGE_TABLE_ROW_VALUE,
    GROUPS_COUNT_ON_PREDEFINED_GROUPS_PAGE,
    KEY_METRIC_CAPTION,
    LIST_USER_IDENTIFIER,
    REPAIR_REQUESTS_COUNT,
    SQL_RESULTS_MAP,
    TABLE_CELL_VALUE,
    TABLE_CELL_VALUE_BEFORE_CLICK_ON_ROW_NUMBER,
    TABLE_CELL_VALUE_IN_INPUT,
    TABLE_COLUMN_CONTENT,
    TABLE_CONTENT,
    TABLE_CUSTOM_TICKED_COLUMN_VALUES,
    TABLE_DISPLAY_INDICATOR_CURRENT_PAGE_ITEMS_COUNT,
    TABLE_DISPLAY_INDICATOR_TOTAL_ITEMS_COUNT,
    USER_ACTIVITY_REPORT_CELL_LINK_ITEMS_COUNT,
    USER_CREDENTIALS,
    VRS_CONTACT_INFO_EMAIL,
    VRS_LOCATION,
    VRS_PENSKE_UNIT,
    VRS_REPAIR_SUB_CATEGORY
}
